# Generated by Django 5.2.14 on 2026-05-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='normalizeddatarecord',
            name='activity_date_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='normalizeddatarecord',
            name='activity_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='normalizeddatarecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Issues')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='normalizeddatarecord',
            index=models.Index(fields=['status', 'created_at'], name='api_normali_status_82919f_idx'),
        ),
    ]
